services:
  postgres:
    image: postgres:latest
    container_name: odoo_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./odoo_postgres_data:/var/lib/postgresql/data

  odoo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: odoo_container
    depends_on:
      - postgres
    ports:
      - "${ODOO_PORT}:8069"
    environment:
      HOST: ${POSTGRES_HOST}
      USER: ${POSTGRES_USER}
      PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./odoo_data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./backup:/backup

volumes:
  odoo_postgres_data:
  odoo_data:
